//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CleanArchitecture.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class InitialV3 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "identity_document",
                table: "customers",
                newName: "identity_document_value");

            migrationBuilder.AddColumn<int>(
                name: "identity_document_type",
                table: "customers",
                type: "integer",
                nullable: false,
                defaultValue: 0);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "identity_document_type",
                table: "customers");

            migrationBuilder.RenameColumn(
                name: "identity_document_value",
                table: "customers",
                newName: "identity_document");
        }
    }
}
